function initTranslations(cityTitle, isCityTranslation) {
    var translation = {
        source: {
            title: "Who would you like to hook up?",
            text01: "Who",
            text02: "would you like to",
            text03: "hook up?",
            text04: "YOU",
            text05: "YOU",
            text06: "How often would you like to be intimate?",
            text07: "Every day",
            text08: "5 - 7 times a week",
            text09: "3 - 5 times a week",
            text10: "1 - 3 times a week",
            text11: "A couple of times a month",
            text12: "I want to be together all the time!",
            text13: "What sort of relationship do you prefer?",
            text14: "Occasional meetings",
            text15: "Friendship",
            text16: "Uncommitted relations",
            text17: "Family relations",
            text18: "Intimate relations",
            text19: "Do you like going on dates?",
            text20: "Yes",
            text21: "No",
            text22: "Is intimacy important to you on the first date?",
            text23: "Yes",
            text24: "No",
            text25: "What age of women is a best match for you?",
            text26: "Thank you.",
            text27: "You may now see our list and photos of women who are in your area and meet your preferences. Again, please keep their identity a secret",
            text28: "Click on the 'Continue' button search with your zip/postal code.",
            text29: "Continue",
        },
        en: {
            title: "Who would you like to hook up?",
            text01: "Who",
            text02: "would you like to",
            text03: "hook up?",
            text04: "YOU",
            text05: "YOU",
            text06: "How often would you like to be intimate?",
            text07: "Every day",
            text08: "5 - 7 times a week",
            text09: "3 - 5 times a week",
            text10: "1 - 3 times a week",
            text11: "A couple of times a month",
            text12: "I want to be together all the time!",
            text13: "What sort of relationship do you prefer?",
            text14: "Occasional meetings",
            text15: "Friendship",
            text16: "Uncommitted relations",
            text17: "Family relations",
            text18: "Intimate relations",
            text19: "Do you like going on dates?",
            text20: "Yes",
            text21: "No",
            text22: "Is intimacy important to you on the first date?",
            text23: "Yes",
            text24: "No",
            text25: "What age of women is a best match for you?",
            text26: "Thank you.",
            text27: "You may now see our list and photos of women who are in your area and meet your preferences. Again, please keep their identity a secret",
            text28: "Click on the 'Continue' button search with your zip/postal code.",
            text29: "Continue",
        },
        es: {
            title: "¿Con quién te gustaría enganchar?",
            text01: "¿Con quién",
            text02: "te gustaría",
            text03: "enganchar?",
            text04: "TÚ",
            text05: "TÚ",
            text06: "¿Con qué frecuencia te gustaría ser íntimo?",
            text07: "Todos los días",
            text08: "De 5 a 7 veces por semana",
            text09: "De 3 a 5 veces por semana",
            text10: "De 1 a 3 veces por semana",
            text11: "Un par de veces al mes",
            text12: "¡Quiero estar juntos todo el tiempo!",
            text13: "¿Qué tipo de relación prefieres?",
            text14: "Encuentros ocasionales",
            text15: "Amistad",
            text16: "Relaciones no comprometidas",
            text17: "Relaciones familiares",
            text18: "Relaciones íntimas",
            text19: "¿Te gusta salir en citas?",
            text20: "Sí",
            text21: "No",
            text22: "¿Es importante la intimidad para ti en la primera cita?",
            text23: "Sí",
            text24: "No",
            text25: "¿Qué edad de mujeres es la mejor para ti?",
            text26: "Gracias.",
            text27: "Ahora puedes ver nuestra lista y fotos de mujeres que están en tu área y cumplen con tus preferencias. Por favor, mantén su identidad en secreto.",
            text28: "Haz clic en el botón 'Continuar' para buscar con tu código postal.",
            text29: "¡Continuar!",
        },
        fr: {
            title: "Avec qui voudrais-tu te brancher?",
            text01: "Avec qui",
            text02: "voudrais-tu",
            text03: "te brancher?",
            text04: "TU",
            text05: "TU",
            text06: "À quelle fréquence aimerais-tu être intime?",
            text07: "Chaque jour",
            text08: "5 à 7 fois par semaine",
            text09: "3 à 5 fois par semaine",
            text10: "1 à 3 fois par semaine",
            text11: "Quelques fois par mois",
            text12: "Je veux être ensemble tout le temps!",
            text13: "Quel genre de relation préférez-vous?",
            text14: "Rencontres occasionnelles",
            text15: "Amitié",
            text16: "Relations non engagées",
            text17: "Relations familiales",
            text18: "Relations intimes",
            text19: "Aimez-vous aller à des rendez-vous?",
            text20: "Oui",
            text21: "Non",
            text22: "L'intimité est-elle importante pour vous lors du premier rendez-vous?",
            text23: "Oui",
            text24: "Non",
            text25: "Quel âge de femmes vous correspond le mieux?",
            text26: "Merci.",
            text27: "Vous pouvez maintenant voir notre liste et les photos des femmes qui sont dans votre région et qui correspondent à vos préférences. Veuillez également garder leur identité secrète.",
            text28: "Cliquez sur le bouton 'Continuer' pour rechercher avec votre code postal.",
            text29: "Continuer!",
        },
        it: {
            title: "Con chi vorresti agganciarti?",
            text01: "Con chi",
            text02: "vorresti",
            text03: "agganciarti?",
            text04: "TU",
            text05: "TU",
            text06: "Con quale frequenza vorresti essere intimo?",
            text07: "Ogni giorno",
            text08: "5-7 volte a settimana",
            text09: "3-5 volte a settimana",
            text10: "1-3 volte a settimana",
            text11: "Un paio di volte al mese",
            text12: "Voglio essere insieme tutto il tempo!",
            text13: "Che tipo di relazione preferisci?",
            text14: "Incontri occasionali",
            text15: "Amicizia",
            text16: "Relazioni non impegnate",
            text17: "Relazioni familiari",
            text18: "Relazioni intime",
            text19: "Ti piace uscire a fare incontri?",
            text20: "Sì",
            text21: "No",
            text22: "L'intimità è importante per te al primo appuntamento?",
            text23: "Sì",
            text24: "No",
            text25: "Quale età di donne è la migliore per te?",
            text26: "Grazie.",
            text27: "Ora puoi vedere la nostra lista e le foto delle donne che si trovano nella tua zona e che corrispondono alle tue preferenze. Ti preghiamo di mantenere segreta la loro identità.",
            text28: "Clicca sul pulsante 'Continua' per cercare con il tuo codice postale.",
            text29: "Continua!",
        },
        nl: {
            title: "Met wie wil je aansluiten?",
            text01: "Met wie",
            text02: "wil je",
            text03: "aansluiten?",
            text04: "JIJ",
            text05: "JIJ",
            text06: "Hoe vaak wil je intiem zijn?",
            text07: "Elke dag",
            text08: "5-7 keer per week",
            text09: "3-5 keer per week",
            text10: "1-3 keer per week",
            text11: "Een paar keer per maand",
            text12: "Ik wil de hele tijd samen zijn!",
            text13: "Wat voor soort relatie geef je de voorkeur?",
            text14: "Af en toe ontmoeten",
            text15: "Vriendschap",
            text16: "Ongebonden relaties",
            text17: "Familierelaties",
            text18: "Intieme relaties",
            text19: "Hou je van daten?",
            text20: "Ja",
            text21: "Nee",
            text22: "Is intimiteit belangrijk voor jou op de eerste date?",
            text23: "Ja",
            text24: "Nee",
            text25: "Welke leeftijd van vrouwen past het beste bij jou?",
            text26: "Bedankt.",
            text27: "Je kunt nu onze lijst en foto's van vrouwen bekijken die zich in jouw omgeving bevinden en aan jouw voorkeuren voldoen. Houd ook hier hun identiteit geheim.",
            text28: "Klik op de knop 'Doorgaan' om te zoeken met jouw postcode.",
            text29: "Doorgaan!",
        },
        no: {
            title: "Hvem vil du koble til?",
            text01: "Hvem vil",
            text02: "du koble",
            text03: "til?",
            text04: "DU",
            text05: "DU",
            text06: "Hvor ofte vil du være intim?",
            text07: "Hver dag",
            text08: "5-7 ganger i uken",
            text09: "3-5 ganger i uken",
            text10: "1-3 ganger i uken",
            text11: "Et par ganger i måneden",
            text12: "Jeg vil være sammen hele tiden!",
            text13: "Hva slags forhold foretrekker du?",
            text14: "Tilfeldige møter",
            text15: "Vennskap",
            text16: "Uforpliktende forhold",
            text17: "Familieforhold",
            text18: "Intime forhold",
            text19: "Liker du å dra på stevnemøter?",
            text20: "Ja",
            text21: "Nei",
            text22: "Er intimitet viktig for deg på første date?",
            text23: "Ja",
            text24: "Nei",
            text25: "Hvilken aldersgruppe av kvinner passer best for deg?",
            text26: "Takk.",
            text27: "Nå kan du se vår liste og bilder av kvinner som er i ditt område og som møter dine preferanser. Vennligst hold identiteten deres hemmelig.",
            text28: "Klikk på 'Fortsett'-knappen for å søke med postnummeret ditt.",
            text29: "Fortsett!",
        },
        sv: {
            title: "Vem vill du koppla upp dig med?",
            text01: "Vem vill",
            text02: "du koppla upp",
            text03: "dig med?",
            text04: "DU",
            text05: "DU",
            text06: "Hur ofta vill du vara intim?",
            text07: "Varje dag",
            text08: "5-7 gånger i veckan",
            text09: "3-5 gånger i veckan",
            text10: "1-3 gånger i veckan",
            text11: "Ett par gånger i månaden",
            text12: "Jag vill vara tillsammans hela tiden!",
            text13: "Vilken typ av relation föredrar du?",
            text14: "Tillfälliga möten",
            text15: "Vänskap",
            text16: "Oengagerade relationer",
            text17: "Familjerelationer",
            text18: "Intima relationer",
            text19: "Gillar du att gå på dejter?",
            text20: "Ja",
            text21: "Nej",
            text22: "Är intimitet viktigt för dig på första dejten?",
            text23: "Ja",
            text24: "Nej",
            text25: "Vilken åldersgrupp av kvinnor passar bäst för dig?",
            text26: "Tack.",
            text27: "Nu kan du se vår lista och bilder på kvinnor som är i ditt område och uppfyller dina preferenser. Var vänlig och håll deras identitet hemlig.",
            text28: "Klicka på 'Fortsätt'-knappen för att söka med ditt postnummer.",
            text29: "Fortsätt!",
        },
        fi: {
            title: "Kenen kanssa haluaisit kytkeytyä?",
            text01: "Kenen",
            text02: "kanssa haluaisit",
            text03: "kytkeytyä?",
            text04: "SINÄ",
            text05: "SINÄ",
            text06: "Kuinka usein haluaisit olla intiimi?",
            text07: "Joka päivä",
            text08: "5-7 kertaa viikossa",
            text09: "3-5 kertaa viikossa",
            text10: "1-3 kertaa viikossa",
            text11: "Muutama kerta kuukaudessa",
            text12: "Haluan olla yhdessä koko ajan!",
            text13: "Minkä tyyppistä suhdetta suosit?",
            text14: "Satunnaiset tapaamiset",
            text15: "Ystävyys",
            text16: "Sitoutumattomat suhteet",
            text17: "Perhesuhteet",
            text18: "Intiimit suhteet",
            text19: "Pidätkö treffailusta?",
            text20: "Kyllä",
            text21: "Ei",
            text22: "Onko intiimiys sinulle tärkeää ensimmäisellä tapaamisella?",
            text23: "Kyllä",
            text24: "Ei",
            text25: "Mikä ikäryhmä naisissa sopii parhaiten sinulle?",
            text26: "Kiitos.",
            text27: "Nyt voit nähdä listamme ja kuvat alueellasi olevista naisista, jotka vastaavat mieltymyksiäsi. Ole hyvä ja säilytä heidän henkilöllisyytensä salaisuutena.",
            text28: "Klikkaa 'Jatka'-painiketta hakeaksesi postinumerollasi.",
            text29: "Jatka!",
        },
        da: {
            title: "Hvem vil du koble til?",
            text01: "HVEM",
            text02: "VIL DU",
            text03: "koble til?",
            text04: "DU",
            text05: "DU",
            text06: "Hvor ofte vil du være intim?",
            text07: "Hver dag",
            text08: "5-7 gange om ugen",
            text09: "3-5 gange om ugen",
            text10: "1-3 gange om ugen",
            text11: "Et par gange om måneden",
            text12: "Jeg vil være sammen hele tiden!",
            text13: "Hvilken type forhold foretrækker du?",
            text14: "Tilfældige møder",
            text15: "Venskab",
            text16: "Uforpligtende forhold",
            text17: "Familieforhold",
            text18: "Intime forhold",
            text19: "Kan du lide at gå på dates?",
            text20: "Ja",
            text21: "Nej",
            text22: "Er intimitet vigtig for dig på første date?",
            text23: "Ja",
            text24: "Nej",
            text25: "Hvilken aldersgruppe af kvinder passer bedst til dig?",
            text26: "Tak.",
            text27: "Nu kan du se vores liste og billeder af kvinder, der er i dit område og opfylder dine præferencer. Vær venlig at holde deres identitet hemmelig.",
            text28: "Klik på 'Fortsæt'-knappen for at søge med dit postnummer.",
            text29: "Fortsæt!",
        },
        tr: {
            title: "Kiminle bağlanmak istersiniz?",
            text01: "Kiminle",
            text02: "bağlanmak",
            text03: "istersiniz?",
            text04: "SEN",
            text05: "SEN",
            text06: "Ne sıklıkta samimi olmak istersiniz?",
            text07: "Her gün",
            text08: "Haftada 5-7 kez",
            text09: "Haftada 3-5 kez",
            text10: "Haftada 1-3 kez",
            text11: "Aylık birkaç kez",
            text12: "Her zaman birlikte olmak istiyorum!",
            text13: "Hangi tür ilişkiyi tercih edersin?",
            text14: "Zaman zaman buluşmalar",
            text15: "Arkadaşlık",
            text16: "Bağlayıcı olmayan ilişkiler",
            text17: "Aile ilişkileri",
            text18: "Samimi ilişkiler",
            text19: "Randevulara gitmekten hoşlanır mısın?",
            text20: "Evet",
            text21: "Hayır",
            text22: "İlk buluşmada samimiyet senin için önemli mi?",
            text23: "Evet",
            text24: "Hayır",
            text25: "Hangi yaş aralığındaki kadınlar senin için en uygun?",
            text26: "Teşekkür ederim.",
            text27: "Şimdi bölgenizdeki ve tercihlerinize uyan kadınların listesini ve fotoğraflarını görebilirsiniz. Lütfen onların kimliğini gizli tutun.",
            text28: "Posta kodunuzla arama yapmak için 'Devam' düğmesine tıklayın.",
            text29: "Devam et!",
        },
        pl: {
            title: "Z kim chciałbyś się połączyć?",
            text01: "Z kim",
            text02: "chciałbyś się",
            text03: "połączyć?",
            text04: "TY",
            text05: "TY",
            text06: "Jak często chciałbyś być intymny?",
            text07: "Codziennie",
            text08: "5-7 razy w tygodniu",
            text09: "3-5 razy w tygodniu",
            text10: "1-3 razy w tygodniu",
            text11: "Kilka razy w miesiącu",
            text12: "Chcę być razem cały czas!",
            text13: "Jaki rodzaj związku preferujesz?",
            text14: "Okazjonalne spotkania",
            text15: "Przyjaźń",
            text16: "Niezobowiązujące relacje",
            text17: "Relacje rodzinne",
            text18: "Relacje intymne",
            text19: "Czy lubisz chodzić na randki?",
            text20: "Tak",
            text21: "Nie",
            text22: "Czy intymność jest dla Ciebie ważna już przy pierwszej randce?",
            text23: "Tak",
            text24: "Nie",
            text25: "W jakim przedziale wiekowym kobiety najlepiej pasują do Ciebie?",
            text26: "Dziękuję.",
            text27: "Teraz możesz zobaczyć naszą listę i zdjęcia kobiet w Twojej okolicy, które spełniają Twoje preferencje. Proszę zachować ich tożsamość w tajemnicy.",
            text28: "Kliknij przycisk 'Kontynuuj', aby szukać według kodu pocztowego.",
            text29: "Kontynuuj!",
        },
        de: {
            title: "An wen möchtest du dich anschließen?",
            text01: "An wen",
            text02: "möchtest du dich",
            text03: "anschließen?",
            text04: "DU",
            text05: "DU",
            text06: "Wie oft möchtest du intim sein?",
            text07: "Jeden Tag",
            text08: "5-7 Mal pro Woche",
            text09: "3-5 Mal pro Woche",
            text10: "1-3 Mal pro Woche",
            text11: "Ein paar Mal im Monat",
            text12: "Ich möchte die ganze Zeit zusammen sein!",
            text13: "Was für eine Art Beziehung bevorzugst du?",
            text14: "Gelegentliche Treffen",
            text15: "Freundschaft",
            text16: "Unverbindliche Beziehungen",
            text17: "Familiäre Beziehungen",
            text18: "Intime Beziehungen",
            text19: "Gehst du gerne auf Dates?",
            text20: "Ja",
            text21: "Nein",
            text22: "Ist Intimität für dich beim ersten Date wichtig?",
            text23: "Ja",
            text24: "Nein",
            text25: "Welches Alter von Frauen passt am besten zu dir?",
            text26: "Danke.",
            text27: "Sie können nun unsere Liste und Fotos von Frauen sehen, die sich in Ihrer Umgebung befinden und Ihren Vorlieben entsprechen. Bitte halten Sie auch hier ihre Identität geheim.",
            text28: "Klicken Sie auf die Schaltfläche 'Weiter', um mit Ihrem Postleitzahlen-Code zu suchen.",
            text29: "Weiter!",

        },
        ru: {
            title: "С кем бы ты хотел переспать?",
            text01: "С кем",
            text02: "бы ты хотел",
            text03: "переспать?",
            text04: "ВЫ",
            text05: "ВЫ",
            text06: "Как часто вы бы хотели интимной близости?",
            text07: "Каждый день",
            text08: "5 - 7 раз в неделю",
            text09: "3 - 5 раз в неделю",
            text10: "1 - 3 раза в неделю",
            text11: "Несколько раз в месяц",
            text12: "Я хочу быть вместе все время!",
            text13: "Какой вид отношений вы предпочитаете?",
            text14: "Случайные встречи",
            text15: "Дружба",
            text16: "Непостоянные отношения",
            text17: "Семейные отношения",
            text18: "Интимные отношения",
            text19: "Вам нравится ходить на свидания?",
            text20: "Да",
            text21: "Нет",
            text22: "Важна ли для вас близость с первого свидания?",
            text23: "Да",
            text24: "Нет",
            text25: "Какой возраст женщин наилучшим образом соответствует вашему запросу?",
            text26: "Спасибо.",
            text27: "Теперь вы можете просмотреть список и фотографии женщин, находящихся в вашем районе и соответствующих вашим предпочтениям. Пожалуйста, сохраняйте их личность в секрете.",
            text28: "Нажмите кнопку 'Продолжить' для поиска с использованием вашего почтового индекса",
            text29: "Продолжить",
        },
        cs: {
            title: "S kým by sis chtěl připojit?",
            text01: "S kým by",
            text02: "sis chtěl",
            text03: "připojit?",
            text04: "TY",
            text05: "TY",
            text06: "Jak často byste chtěli být intimní?",
            text07: "Každý den",
            text08: "5-7krát týdně",
            text09: "3-5krát týdně",
            text10: "1-3krát týdně",
            text11: "Několikrát měsíčně",
            text12: "Chci být stále spolu!",
            text13: "Jaký typ vztahu upřednostňuješ?",
            text14: "Občasná setkání",
            text15: "Přátelství",
            text16: "Nezávazné vztahy",
            text17: "Rodinné vztahy",
            text18: "Intimní vztahy",
            text19: "Líbí se ti chodit na rande?",
            text20: "Ano",
            text21: "Ne",
            text22: "Je pro tebe důležitá intimita už při prvním rande?",
            text23: "Ano",
            text24: "Ne",
            text25: "V jakém věkovém rozmezí jsou pro tebe ženy nejlepším zápasem?",
            text26: "Děkuji.",
            text27: "Nyní můžeš vidět náš seznam a fotografie žen, které jsou ve tvém okolí a odpovídají tvým preferencím. Prosím, uchovávej jejich totožnost v tajnosti.",
            text28: "Klikni na tlačítko 'Pokračovat' pro hledání s tvým PSČ.",
            text29: "Pokračovat!",
        },
        el: {
            title: "Σε ποιον θα ήθελες να συνδεθείς;",
            text01: "Σε ποιον",
            text02: "θα ήθελες να",
            text03: "συνδεθείς;",
            text04: "ΕΣΥ",
            text05: "ΕΣΥ",
            text06: "Πόσο συχνά θα θέλατε να είστε ερωτικοί;",
            text07: "Καθημερινά",
            text08: "5-7 φορές την εβδομάδα",
            text09: "3-5 φορές την εβδομάδα",
            text10: "1-3 φορές την εβδομάδα",
            text11: "Μερικές φορές το μήνα",
            text12: "Θέλω να είμαι μαζί όλη την ώρα!",
            text13: "Ποιον τύπο σχέσης προτιμάς;",
            text14: "Περιστασιακές συναντήσεις",
            text15: "Φιλία",
            text16: "Ανεπίσημες σχέσεις",
            text17: "Οικογενειακές σχέσεις",
            text18: "Ερωτικές σχέσεις",
            text19: "Σου αρέσει να βγαίνεις ραντεβού;",
            text20: "Ναι",
            text21: "Όχι",
            text22: "Είναι σημαντική για σένα η επικοινωνία από την πρώτη συνάντηση;",
            text23: "Ναι",
            text24: "Όχι",
            text25: "Ποια ηλικιακή ομάδα γυναικών ταιριάζει καλύτερα με εσένα;",
            text26: "Ευχαριστώ.",
            text27: "Τώρα μπορείς να δεις τη λίστα και τις φωτογραφίες γυναικών που είναι στην περιοχή σου και πληρούν τις προτιμήσεις σου. Κράτα την ταυτότητά τους μυστική.",
            text28: "Πάτα το κουμπί 'Συνέχεια' για να αναζητήσεις με τον ταχυδρομικό σου κώδικα.",
            text29: "Συνέχισε!",
        },
        hu: {
            title: "Kihez szeretnél csatlakozni?",
            text01: "Kihez",
            text02: "szeretnél",
            text03: "csatlakozni?",
            text04: "TE",
            text05: "TE",
            text06: "Milyen gyakran szeretnél intim lenni?",
            text07: "Minden nap",
            text08: "5-7 alkalommal hetente",
            text09: "3-5 alkalommal hetente",
            text10: "1-3 alkalommal hetente",
            text11: "Havonta néhány alkalommal",
            text12: "Mindig együtt akarok lenni!",
            text13: "Milyen típusú kapcsolatot részesítesz előnyben?",
            text14: "Véletlenszerű találkozások",
            text15: "Barátság",
            text16: "Kötelezettségmentes kapcsolatok",
            text17: "Családi kapcsolatok",
            text18: "Intim kapcsolatok",
            text19: "Szeretsz randizni?",
            text20: "Igen",
            text21: "Nem",
            text22: "Fontos számodra az intimitás az első randin?",
            text23: "Igen",
            text24: "Nem",
            text25: "Milyen női korosztály illik hozzád leginkább?",
            text26: "Köszönöm.",
            text27: "Most láthatod a listánkat és a nők fényképeit, akik a környékeden vannak, és megfelelnek az elvárásaidnak. Kérlek, őrizd meg az azonosságukat titokban.",
            text28: "Kattints a 'Folytatás' gombra, hogy keress a irányítószámod szerint.",
            text29: "Folytatás!",
        },
        sl: {
            title: "Koga bi rad priključil?",
            text01: "Koga",
            text02: "bi rad",
            text03: "priključil?",
            text04: "TI",
            text05: "TI",
            text06: "Kako pogosto bi želeli biti intimni?",
            text07: "Vsak dan",
            text08: "5-7 krat na teden",
            text09: "3-5 krat na teden",
            text10: "1-3 krat na teden",
            text11: "Nekajkrat na mesec",
            text12: "Želim biti skupaj ves čas!",
            text13: "Kakšno vrsto razmerja imaš najraje?",
            text14: "Občasna srečanja",
            text15: "Prijateljstvo",
            text16: "Nezavezane zveze",
            text17: "Družinska razmerja",
            text18: "Intimna razmerja",
            text19: "Rad hodiš na zmenke?",
            text20: "Da",
            text21: "Ne",
            text22: "Je zate intimnost pomembna že na prvem zmenku?",
            text23: "Da",
            text24: "Ne",
            text25: "Katero starostno skupino žensk najbolj vidiš kot primerno zase?",
            text26: "Hvala.",
            text27: "Zdaj lahko vidiš seznam in fotografije žensk v tvoji okolici, ki ustrezajo tvojim željam. Prosim, ohrani njihovo identiteto v tajnosti.",
            text28: "Klikni na gumb 'Nadaljuj' za iskanje po svoji poštni številki.",
            text29: "Nadaljuj!",
        },
        sk: {
            title: "S kým by si chcel pripojiť?",
            text01: "S kým by",
            text02: "si chcel",
            text03: "pripojiť?",
            text04: "TY",
            text05: "TY",
            text06: "Ako často by ste chceli byť intímny?",
            text07: "Každý deň",
            text08: "5-7 krát týždenne",
            text09: "3-5 krát týždenne",
            text10: "1-3 krát týždenne",
            text11: "Párkrát do mesiaca",
            text12: "Chcem byť stále spolu!",
            text13: "Aký typ vzťahu preferuješ?",
            text14: "Občasné stretnutia",
            text15: "Priateľstvo",
            text16: "Nezáväzné vzťahy",
            text17: "Rodinné vzťahy",
            text18: "Intímne vzťahy",
            text19: "Máš rád randenie?",
            text20: "Áno",
            text21: "Nie",
            text22: "Je pre teba dôležitá intimita už na prvom rande?",
            text23: "Áno",
            text24: "Nie",
            text25: "V akej vekovej skupine žien vidíš svoj najlepší zápas?",
            text26: "Ďakujem.",
            text27: "Teraz môžeš vidieť našu listu a fotky žien v tvojom okolí, ktoré spĺňajú tvoje preferencie. Prosím, zachovaj ich identitu v tajnosti.",
            text28: "Klikni na tlačidlo 'Pokračovať' pre vyhľadávanie podľa tvojho PSČ.",
            text29: "Pokračuj!",
        },
        hr: {
            title: "S kim biste htjeli spojiti?",
            text01: "S kim",
            text02: "biste htjeli",
            text03: "spojiti?",
            text04: "TI",
            text05: "TI",
            text06: "Koliko često biste voljeli biti intimni?",
            text07: "Svaki dan",
            text08: "5-7 puta tjedno",
            text09: "3-5 puta tjedno",
            text10: "1-3 puta tjedno",
            text11: "Par puta mjesečno",
            text12: "Želim biti zajedno uvijek!",
            text13: "Kakav tip odnosa preferiraš?",
            text14: "Povremeni susreti",
            text15: "Prijateljstvo",
            text16: "Neobavezni odnosi",
            text17: "Obiteljski odnosi",
            text18: "Intimni odnosi",
            text19: "Volis li ići na spojeve?",
            text20: "Da",
            text21: "Ne",
            text22: "Je li ti važna intimnost već na prvom spoju?",
            text23: "Da",
            text24: "Ne",
            text25: "Koja dobna skupina žena ti najbolje odgovara?",
            text26: "Hvala ti.",
            text27: "Sada možeš vidjeti naš popis i fotografije žena koje su u tvojoj blizini i koje odgovaraju tvojim preferencijama. Molim te da čuvaš njihov identitet u tajnosti.",
            text28: "Pritisni gumb 'Nastavi' kako bi pretražio s poštanskim brojem.",
            text29: "Nastavi!",
        },
        ro: {
            title: "La cine ați dori să vă alăturați?",
            text01: "Cu cine",
            text02: "ați dori să",
            text03: "vă întâlniți?",
            text04: "TU",
            text05: "TU",
            text06: "Cât de des ai vrea să ai intim?",
            text07: "În fiecare zi",
            text08: "5-7 ori pe săptămână",
            text09: "3-5 ori pe săptămână",
            text10: "1-3 ori pe săptămână",
            text11: "De câteva ori pe lună",
            text12: "Vreau să fiu tot timpul împreună!",
            text13: "Ce fel de relație preferi?",
            text14: "Întâlniri ocazionale",
            text15: "Prietenie",
            text16: "Relații neangajate",
            text17: "Relații de familie",
            text18: "Relații intime",
            text19: "Îți place să mergi la întâlniri?",
            text20: "Da",
            text21: "Nu",
            text22: "Este importantă intimitatea pentru tine încă de la prima întâlnire?",
            text23: "Da",
            text24: "Nu",
            text25: "Ce vârstă de femei consideri că se potrivește cel mai bine cu tine?",
            text26: "Mulțumesc.",
            text27: "Acum poți vedea lista și fotografiile femeilor care sunt în zona ta și se potrivesc preferințelor tale. Te rog să păstrezi identitatea lor în secret.",
            text28: "Apasă pe butonul 'Continuă' pentru a căuta cu codul tău poștal.",
            text29: "Continuați!",
        },
        bg: {
            title: "Към кого бихте искали да се присъедините?",
            text01: "Към кого",
            text02: "бихте искали да",
            text03: "се присъедините?",
            text04: "ТИ",
            text05: "ТИ",
            text06: "Колко често бихте искали да бъдете интимни?",
            text07: "Всеки ден",
            text08: "5-7 пъти седмично",
            text09: "3-5 пъти седмично",
            text10: "1-3 пъти седмично",
            text11: "Няколко пъти месечно",
            text12: "Искам да сме заедно постоянно!",
            text13: "Какъв вид отношение предпочиташ?",
            text14: "Случайни срещи",
            text15: "Приятелство",
            text16: "Неангажирани отношения",
            text17: "Семейни отношения",
            text18: "Интимни отношения",
            text19: "Харесва ли ти да ходиш на срещи?",
            text20: "Да",
            text21: "Не",
            text22: "За теб е ли важна близостта още на първата среща?",
            text23: "Да",
            text24: "Не",
            text25: "В какъв възрастов диапазон жени те интересуват най-много?",
            text26: "Благодаря ти.",
            text27: "Сега можеш да видиш нашия списък и снимки на жени, които са в твоята зона и отговарят на твоите предпочитания. Моля, запази техния идентитет в тайна.",
            text28: "Натисни бутона 'Продължи', за да търсиш с пощенския си код.",
            text29: "Продължи!",
        },
        pt: {
            title: "Com quem gostarias de ligar?",
            text01: "Com quem",
            text02: "gostarias de",
            text03: "ligar?",
            text04: "VOCÊ",
            text05: "VOCÊ",
            text06: "Com que frequência gostaria de ser íntimo?",
            text07: "Todo dia",
            text08: "5-7 vezes por semana",
            text09: "3-5 vezes por semana",
            text10: "1-3 vezes por semana",
            text11: "Algumas vezes por mês",
            text12: "Quero estar junto o tempo todo!",
            text13: "Que tipo de relacionamento você prefere?",
            text14: "Encontros ocasionais",
            text15: "Amizade",
            text16: "Relações não comprometidas",
            text17: "Relações familiares",
            text18: "Relações íntimas",
            text19: "Você gosta de sair em encontros?",
            text20: "Sim",
            text21: "Não",
            text22: "A intimidade é importante para você no primeiro encontro?",
            text23: "Sim",
            text24: "Não",
            text25: "Qual faixa etária de mulheres é a melhor para você?",
            text26: "Obrigado.",
            text27: "Agora você pode ver nossa lista e fotos de mulheres que estão na sua área e atendem às suas preferências. Por favor, mantenha a identidade delas em segredo.",
            text28: "Clique no botão 'Continuar' para pesquisar com o seu código postal.",
            text29: "Continuar!",
        },
        he: {
            title: "מהי תרצו להתחבר?",
            text01: "להתחבר",
            text02: "תרצו",
            text03: "מהי?",
            text04: "אתה",
            text05: "אתה",
            text06: "באיזו תדירות תרצה להיות אינטימי?",
            text07: "כל יום",
            text08: "5-7 פעמים בשבוע",
            text09: "3-5 פעמים בשבוע",
            text10: "1-3 פעמים בשבוע",
            text11: "פעמיים בחודש",
            text12: "אני רוצה שנהיה יחד תמיד!",
            text13: "איזה סוג של יחס אתה מעדיף?",
            text14: "פגישות אקראיות",
            text15: "ידידות",
            text16: "יחסים לא מחייבים",
            text17: "יחסי משפחה",
            text18: "יחסים אינטימיים",
            text19: "אתה אוהב לצאת לדייטים?",
            text20: "כן",
            text21: "לא",
            text22: "האם האינטימיות חשובה לך בדייט הראשון?",
            text23: "כן",
            text24: "לא",
            text25: "באיזה קבוצת גיל נשים הכי מתאימה לך?",
            text26: "תודה לך.",
            text27: "עכשיו אתה יכול לראות את רשימתנו ואת התמונות של נשים שבאזור שלך ומתאימות להעדפותיך. שוב, אנא שמור על זהותן בסוד.",
            text28: "לחץ על הכפתור 'המשך' לחיפוש עם מיקוד שלך.",
            text29: "!המשך",
        },
    };

    var availableLang = translation_available(translation);

    if (!isCityTranslation) {
        for (var x in translation["source"]) {
            replace_text(availableLang, x, translation, isCityTranslation);
        }
    } else {
        var cityArr = ['', ''];

        for (var x in cityArr) {
            replace_text(availableLang, cityArr[x], translation, isCityTranslation);
        }
    }
}

function replace_text(lang, text, translation, isCityTranslation) {
    if (isCityTranslation && text.indexOf('_replace') !== -1) {
        var x = document.getElementById(text.replace('_replace', ''));
    } else {
        var x = document.getElementById(text);
    }

    if (x && translation[lang][text] != undefined) {
        if (x.placeholder != undefined) {
            x.placeholder = translation[lang][text];
        } else if (x.tagName === 'IFRAME') {
            x.src = translation[lang][text];
        } else {
            x.innerHTML = translation[lang][text];
        }
    } else {
        //console.log("element not Found: " + text);
    }
}

function translation_available(objTrls) {
    if (objTrls[browserLang] && objTrls[browserLang].title && objTrls[browserLang].title.length) {
        return browserLang;
    } else {
        console.log("translation not Found: " + browserLang);
        return "source";
    }
}

function getParameterByName(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(location.search);
    return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}

function detect_language() {
    var forceLang = getParameterByName("lang");

    if (forceLang) {
        return forceLang;
    } else {
        var userLang = navigator.languages && navigator.languages[0] || navigator.language || navigator.userLanguage;
        if (userLang == "zh-CN" || userLang == "zh-SG" || userLang == "zh-MY" || userLang == "zh-CHS") {
            userLang = "zh-Hans";
        } else if (userLang == "zh-HK" || userLang == "zh-MO" || userLang == "zh-TW" || userLang == "zh-CHT") {
            userLang = "zh-Hant";
        } else if (userLang == "no" || userLang == "nb" || userLang == "nb-NO" || userLang == "nn-NO") {
            userLang = "no";
        } else if (userLang.length > 2) {
            userLang = userLang[0] + userLang[1];
        }
        return userLang;
    }
}

var cityTitle = '';
var browserLang = detect_language();
$('body').addClass('site-lang-' + browserLang);

initTranslations(cityTitle, false);

function changeCity(data) {
    data.city["pt"] = data.city["pt-BR"];

    if (data.city[browserLang] && data.city[browserLang].length) {
        cityTitle = data.city[browserLang];
        initTranslations(cityTitle, true);
    }
}

setTimeout(function() {
    if (geoRefData) {
        changeCity(geoRefData);
    } else {
        var request = new XMLHttpRequest();
        request.open('GET', 'https://bigdatajsext.com/ExtService.svc/getextparams', true);

        request.onload = function() {
            if (request.status >= 200 && request.status < 400) {
                var data = JSON.parse(request.responseText);
                changeCity(data);
            } else {
                console.log('Server returned an error');
            }
        };

        request.onerror = function() {
            console.log('Error: ' + request.status);
        };

        request.send();
    }
}, 1000);